# Generated by Django 4.1.7 on 2023-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventusers',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
